[workspace]
resolver = "2"
package.version = "0.1.0"
package.edition = "2021"

members = ["cli"]

[workspace.lints.rust]
unused_must_use = "deny"

[workspace.lints.clippy]
unwrap_used = "deny"

[workspace.dependencies]
config-manager = { version = "^0.4" }
serde = { version = "^1.0" }
thiserror = { version = "^2.0" }
toml = { version = "^0.8" }
tracing = { version = "^0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
